# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


  lane :ios do |options|
    increment_version_number(
      version_number: options[:appVersion]
    )
    increment_build_number(xcodeproj: "nubanktest.xcodeproj")
    build_app(scheme: "nubanktest")
    upload_to_testflight
  end
