# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :android do |options|
    gradle(task: "clean assembleRelease",
      properties: {
        "versionName" => options[:appVersion]
      }
    )
    hockey(api_token: "007b5218d4db41cbbc501c5b07d57f78", 
      apk: "./app/build/outputs/apk/app-release-unsigned.apk"
    )
  end
